#!/usr/bin/env bash

version="9.1.0414"

if [[ ! -e ~/make-builds ]]; then
    mkdir -p ~/make-builds
fi

cd ~/make-builds

if [[ ! -e ~/make-builds/vim-$version ]]; then
    echo "Downloading vim version $version"
    curl -o vim-$version.tar.gz https://codeload.github.com/vim/vim/tar.gz/refs/tags/v$version

    echo "Unpacking vim-$version"
    tar xvf vim-$version.tar.gz

    echo "Removing tarball"
    rm vim-$version.tar.gz
fi

sudo apt install libxt-dev libncurses-dev

cd vim-$version

echo "Cleaning..."
make distclean
make clean

echo "Configuring..."
./configure \
    --with-features=huge \
    --enable-python3interp \
    --with-python3-command=/usr/bin/python3 \
    --with-x \
    --disable-gui

sudo make install
