#!/usr/bin/env bash

dirs_to_update=(~/Documents ~/tmux_config ~/.vim ~/.config/nvim ~/projscripts)

for dir in ${dirs_to_update[@]}; do
	if [ -e $dir ]; then
		cd $dir
		echo "Syncing $dir"
		git pull
	else
		echo "WARNING: $dir is not present! Please clone the repo"
	fi
done

# sync passwords
echo "Syncing passwords"
pass git pull
