#!/usr/bin/env bash

. /etc/os-release

if [[ ! -d $HOME/make-builds/vim ]]; then
    git clone https://github.com/vim/vim.git ~/make-builds/vim
fi

if [[ $ID == "fedora" ]] || [[ $ID == "nobara" ]]; then
    echo "Installing dependencies for $ID..."
    sudo dnf install libXt-devel python3-devel
elif [[ $ID == "ubuntu" ]]
    echo "Installing dependencies for $ID..."
    sudo apt install python3-dev
fi

cd $HOME/make-builds/vim

echo "Cleaning..."
make distclean
make clean

echo "Configuring..."
if [[ $ID == "fedora" ]] || [[ $ID == "nobara" ]]; then
    ./configure \
        --with-features=huge \
        --enable-python3interp \
        --with-python3-command=/usr/bin/python3 \
        --with-python3-config-dir=/usr/lib64/python3.11/config-3.11-x86_64-linux-gnu/ \
        --with-x \
        --disable-gui
elif [[ $ID == "ubuntu" ]]
    ./configure \
        --with-features=huge \
        --enable-python3interp \
        --with-python3-command=/usr/bin/python3 \
        --with-x \
        --disable-gui
fi

sudo make install
