#!/usr/bin/env bash

function switch_to_window() {
    if [[ -z $TMUX ]]; then
        tmux a -t manzil:fe
    else
        tmux switch-client -t manzil:fe
    fi
}

tmux has-session -t manzil 2>/dev/null

if [[ $? == 1 ]]; then
    tmux new -ds manzil -c $HOME/src/ManzilApp/manzil-fe
    tmux rename-window -t manzil:0 fe
fi

switch_to_window 2>/dev/null

if [[ $? == 1 ]]; then
    tmux new-window -t manzil -n fe -c $HOME/src/ManzilApp/manzil-fe
fi
