#!/usr/bin/env bash

selected_path=$(find ~/src ~/Documents ~/projscripts ~/postgresql -type d \( -name node_modules -o -name .git -o -name __pycache__ \) -prune -o -type d -print | fzf)
selected_dir=$(basename $selected_path)
current_session=$(tmux display-message -p '#S')
target_window="$current_session:$selected_dir"

tmux switch-client -t $target_window 2>/dev/null

if [[ $? == 1 ]]; then
    tmux new-window -n $selected_dir -c $selected_path
fi
