#!/usr/bin/env bash

function find_relevant_directories() {
    directories=$(find ~/src ~/Documents ~/projscripts ~/postgresql ~/tmux_config ~/.vim ~/.config/nvim ~/.config/alacritty ~/.config/i3 ~/.config/i3status -type d \( -name node_modules -o -name .git -o -name __pycache__ \) -prune -o -type d -print | fzf)
    echo $directories
}
